name: "iris-data-cache"
description: "create and cache the iris test data"

inputs:
  cache_build:
    description: "data cache build number"
    required: false
    default: "0"
  env_name:
    description: "environment name"
    required: true
  version:
    description: "iris test data version"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: data-cache
      with:
        path: ~/iris-test-data
        key: ${{ runner.os }}-iris-test-data-${{ inputs.env_name }}-v${{ inputs.version }}-b${{ inputs.cache_build }}

    - if: steps.data-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget --quiet https://github.com/SciTools/iris-test-data/archive/v${{ inputs.version }}.zip -O iris-test-data.zip
        unzip -q iris-test-data.zip
        mv iris-test-data-${{ inputs.version }} ~/iris-test-data
