# Updates the environment lock files. See the called workflow in the
# scitools/workflows repo for more details.

name: Refresh Lockfiles


on:
  workflow_dispatch:
  schedule:
    # Run once a week on a Saturday night 
    # N.B. "should" be quoted, according to
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: "1 0 * * 6"

jobs:
  refresh_lockfiles:
    uses: scitools/workflows/.github/workflows/refresh-lockfiles.yml@2024.06.3
    secrets: inherit
