# See https://github.com/actions/stale

name: Stale issues and pull-requests
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  stale:
    if: "github.repository == 'SciTools/iris'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Idle number of days before marking issues/prs stale.
          days-before-stale: 500

          # Idle number of days before closing stale issues/prs.
          days-before-close: 28

          # Comment on the staled issues.
          stale-issue-message: |
            In order to maintain a backlog of relevant issues, we automatically label them as stale after 500 days of inactivity.

            If this issue is still important to you, then please comment on this issue and the stale label will be removed.

            Otherwise this issue will be automatically closed in 28 days time.

          # Comment on the staled prs.
          stale-pr-message: | 
            In order to maintain a backlog of relevant PRs, we automatically label them as stale after 500 days of inactivity.

            If this PR is still important to you, then please comment on this PR and the stale label will be removed.

            Otherwise this PR will be automatically closed in 28 days time.

          # Comment on the staled issues while closed.
          close-issue-message: |
            This stale issue has been automatically closed due to a lack of community activity.
            
            If you still care about this issue, then please either:
              * Re-open this issue, if you have sufficient permissions, or
              * Add a comment pinging `@SciTools/iris-devs` who will re-open on your behalf.

          # Comment on the staled prs while closed.
          close-pr-message: |
            This stale PR has been automatically closed due to a lack of community activity.
            
            If you still care about this PR, then please either:
              * Re-open this PR, if you have sufficient permissions, or
              * Add a comment pinging `@SciTools/iris-devs` who will re-open on your behalf.

          # Label to apply on staled issues. 
          stale-issue-label: Stale

          # Label to apply on staled prs.
          stale-pr-label: Stale

          # Labels on issues exempted from stale.
          exempt-issue-labels: |
            "Status: Blocked,Status: Decision Required,Peloton üö¥‚Äç‚ôÇÔ∏è,Good First Issue"

          # Labels on prs exempted from stale.
          exempt-pr-labels: |
            "Status: Blocked,Status: Decision Required,Peloton üö¥‚Äç‚ôÇÔ∏è,Good First Issue"

          # Max number of operations per run.
          operations-per-run: 300

          # Remove stale label from issues/prs on updates/comments.
          remove-stale-when-updated: true

          # Order to get issues/PRs.
          ascending: true

          # Exempt all issues/prs with milestones from stale.
          exempt-all-milestones: true
